vich_uploader:
    db_driver: orm

    mappings:
        evenementimage:
            uri_prefix: /images/evenement
            upload_destination: '%kernel.project_dir%/public/Upload/evenement'

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
